version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Lima
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - python
    groups:
      patches:
        update-types:
          - patch
      dev-deps:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Lima
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(ci)"
    labels:
      - dependencies
      - github-actions
